version: '3.4'

networks:
  choon-network: {}

volumes:
  choon-sql: {}

services:

  choon.api:
    image: ${DOCKER_REGISTRY-}choonapi
    networks:
      - choon-network
    ports:
      - "2335:80"
      - "2336:443"
    build:
      context: .
      dockerfile: src/Applications/Choon.Api/Dockerfile
    environment:
      FormCheck__AzureStorage__ConnectionString: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1
      SqlOptions__ConnectionString: Server=tcp:sql,1433;User ID=SA;Password=^dEbX2Ew;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    networks:
      - choon-network
    ports:
      - "10010:10000"
      - "10011:10001"
      - "10012:10002"
    entrypoint: "azurite --loose -l /data --oauth=basic --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0 --debug /debug.log"
    labels:
      - chooncompose

  sql:
    image: mcr.microsoft.com/mssql/server
    networks:
      - choon-network
    ports:
      - "1453:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "^dEbX2Ew"
    volumes:
      - choon-sql:/var/opt/mssql