# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  choon.api:
    build:
      context: "D:\\Coding\\Projects\\Choon"
      dockerfile: "Applications/Choon.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "choonapi:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\Stefan\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Coding\\Projects\\Choon\\Applications\\Choon.Api:/app:rw"
    - "D:\\Coding\\Projects\\Choon:/src:rw"
    - "C:\\Users\\Stefan\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.2\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Tools\\Rider\\JetBrains Rider 233.11799.49\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Stefan\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_1_07_17_47_55:/var/opt/rider-debugger:rw"
    working_dir: "/app"
